import { hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { setRequestLocale } from "next-intl/server";
import { routing } from "@/i18n/routing";
import Providers from "@/components/providers";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // حدد الأوزان اللي هتستخدمها
  display: "swap",
  variable: "--font-poppins", // اختياري لو هتستخدمه كـ CSS variable
});

//Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// Generate all possible locale-based route parameters for Next.js to pre-render at build time
export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({ children, params }: LayoutProps) {
  const { locale } = await params;
  // Enable static rendering
  setRequestLocale(locale);
  if (!hasLocale(routing.locales, locale)) {
    return notFound();
  }

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body className={`${poppins.className}`}>
        {/* Providers */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
