import { hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { setRequestLocale } from "next-intl/server";
import { routing } from "@/i18n/routing";
import Providers from "@/components/providers";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-poppins",
});

const chillax = localFont({
  src: [
    { path: "../../../public/fonts/Chillax-Light.woff2", weight: "300", style: "normal" },
    { path: "../../../public/fonts/Chillax-Regular.woff2", weight: "400", style: "normal" },
    { path: "../../../public/fonts/Chillax-Medium.woff2", weight: "500", style: "normal" },
    { path: "../../../public/fonts/Chillax-Semibold.woff2", weight: "600", style: "normal" },
    { path: "../../../public/fonts/Chillax-Bold.woff2", weight: "700", style: "normal" },
  ],
  variable: "--font-chillax",
  display: "swap",
});

//Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// Generate all possible locale-based route parameters for Next.js to pre-render at build time
export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({ children, params }: LayoutProps) {
  const { locale } = await params;
  // Enable static rendering
  setRequestLocale(locale);
  if (!hasLocale(routing.locales, locale)) {
    return notFound();
  }

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body className={`${poppins.variable} ${chillax.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
